In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

## train test split:

In [7]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

## scaling:

In [8]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [9]:
X_train

array([[-0.69956374, -0.2741814 , -0.72832842, ..., -0.68243551,
        -1.48030799, -0.80540539],
       [-0.9698869 ,  1.09387738, -0.98405372, ..., -1.28905181,
         0.21721993, -0.42133374],
       [-0.52701704,  0.55071071, -0.52826837, ...,  0.07894892,
         0.08060113,  0.461869  ],
       ...,
       [ 0.44787183,  0.20137116,  0.42683004, ...,  0.50557332,
         1.68390919,  1.20678433],
       [-0.67655751, -0.1479684 , -0.60569747, ...,  0.60989389,
         2.88992348,  3.03261016],
       [-0.71394263, -0.48829274, -0.74172156, ..., -0.08609556,
        -0.54753132, -0.70709169]])

In [10]:
y_train

297    M
549    B
88     B
106    B
489    M
      ..
149    B
293    B
223    M
31     M
187    B
Name: diagnosis, Length: 455, dtype: object

## Label Encoder:

In [11]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [12]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0])

## Numpy arrays to pytorch tensors:

In [13]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

## Defining the model:

In [16]:
class MySimpleNN():
  def __init__(self,X):

    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

## important parameters:

In [17]:
learning_rate=0.1
epochs=25

## Training Pipeline:

In [18]:
#create model
model=MySimpleNN(X_train_tensor)
model.weights

tensor([[0.0452],
        [0.9019],
        [0.2210],
        [0.0520],
        [0.9242],
        [0.4686],
        [0.8990],
        [0.1026],
        [0.9244],
        [0.7783],
        [0.1228],
        [0.9899],
        [0.4507],
        [0.4811],
        [0.3608],
        [0.3162],
        [0.9855],
        [0.4612],
        [0.4643],
        [0.8856],
        [0.3540],
        [0.5957],
        [0.4286],
        [0.0849],
        [0.9078],
        [0.6631],
        [0.2801],
        [0.2827],
        [0.1920],
        [0.4641]], dtype=torch.float64, requires_grad=True)

In [19]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

to train a model we follow three steps:
1.forward pass

2.loss calculation

3.backward pass

4.parameters update

all these steps are performed in loop upto the numbetr of times we have decided the epoch

In [22]:
#define loop:
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(X_train_tensor)
  # print(y_pred)

  #loss calculation:
  loss=model.loss_function(y_pred,y_train_tensor)
  # #print(f'epoch: {epoch+1},loss: {loss.item()}')

  #backward pass(backpropagation):
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.weights-=-(learning_rate*model.weights.grad)
    model.bias -=-(learning_rate*model.bias.grad)

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 7.320783923766066
Epoch: 2, Loss: 7.320928614694009
Epoch: 3, Loss: 7.321073364685687
Epoch: 4, Loss: 7.321218173722463
Epoch: 5, Loss: 7.321363041784368
Epoch: 6, Loss: 7.321507968850985
Epoch: 7, Loss: 7.3216529549033735
Epoch: 8, Loss: 7.321797999926944
Epoch: 9, Loss: 7.32194310390326
Epoch: 10, Loss: 7.322088266817669
Epoch: 11, Loss: 7.322233488654678
Epoch: 12, Loss: 7.322378769401086
Epoch: 13, Loss: 7.322524109044571
Epoch: 14, Loss: 7.322669507572816
Epoch: 15, Loss: 7.322814964975938
Epoch: 16, Loss: 7.322960481241019
Epoch: 17, Loss: 7.323106056360584
Epoch: 18, Loss: 7.323251690325586
Epoch: 19, Loss: 7.323397383132361
Epoch: 20, Loss: 7.323543134770591
Epoch: 21, Loss: 7.323688945234773
Epoch: 22, Loss: 7.323834814521739
Epoch: 23, Loss: 7.323980742626056
Epoch: 24, Loss: 7.324126729545319
Epoch: 25, Loss: 7.324272775280807

In [23]:
model.weights

tensor([[3.7095],
        [2.8254],
        [4.0356],
        [3.7039],
        [3.4150],
        [4.7792],
        [5.5679],
        [4.8339],
        [3.6149],
        [2.2781],
        [3.4163],
        [1.9563],
        [3.7358],
        [3.6115],
        [1.6007],
        [4.1697],
        [4.1191],
        [4.2315],
        [1.1359],
        [3.6776],
        [4.3948],
        [2.8655],
        [4.6083],
        [4.0491],
        [3.7819],
        [4.8369],
        [4.7502],
        [5.0541],
        [2.5304],
        [3.5250]], dtype=torch.float64, requires_grad=True)

## evaluation:

In [28]:
## model evaluation:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5).float() #->this converts values in y_pred to 0 and 1
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')
# print(y_pred)

Accuracy: 0.5495536923408508